version: "3.8"

services:
  proxy:
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/poll_app/staticfiles
    env_file:
      - ./nginx/.env
    depends_on:
      - web

  web:
    build: .
    command: bash -c "python manage.py migrate &&
             python manage.py collectstatic --clear --noinput &&
             gunicorn poll_app.wsgi:application -b 0.0.0.0:8000 --reload" 
    volumes:
      - static_volume:/poll_app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - ./.env 
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  static_volume:
